// You are given three positive integers num1, num2, and num3.
// The key of num1, num2, and num3 is defined as a four-digit number such that:
// Initially, if any number has less than four digits, it is padded with leading zeros.
// The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
// Return the key of the three numbers without leading zeros (if any).

var generateKey = function(num1, num2, num3) {
    let str1 = "0".repeat(4 - String(num1).length) + num1
    let str2 = "0".repeat(4 - String(num2).length) + num2
    let str3 = "0".repeat(4 - String(num3).length) + num3
    let key = ""

   for(let i = 0; i < 4; i ++){
        key += Math.min(Number(str1[i]),Number(str2[i]),Number(str3[i]) )
   }
   return Number(key)
    
};